package apps

type AppName string

const (
	Sonarr            AppName = "sonarr"
	Radarr            AppName = "radarr"
	Lidarr            AppName = "lidarr"
	Readarr           AppName = "readarr"
	Prowlarr          AppName = "prowlarr"
	Whispar           AppName = "whispar"
	Bazarr            AppName = "bazarr"
	Plex              AppName = "plex"
	Jellyfin          AppName = "jellyfin"
	Emby              AppName = "emby"
	Overseer          AppName = "overseer"
	Tautulli          AppName = "tautulli"
	Nzbget            AppName = "nzbget"
	ruTorrent         AppName = "rutorrent"
	Sabnzbd           AppName = "sabnzbd"
	VueTorrent        AppName = "vuetorrent"
	qBittorrent       AppName = "qbittorrent"
	Deluge            AppName = "deluge"
	Jackett           AppName = "jackett"
	Librespeed        AppName = "librespeed"
	Synclounge        AppName = "synclounge"
	Lazylibrarian     AppName = "lazylibrarian"
	CalibreWeb        AppName = "calibreweb"
	Transmission      AppName = "transmission"
	Mylar             AppName = "mylar"
	Duplicati         AppName = "duplicati"
	Xbackbone         AppName = "xbackbone"
	Filebrowser       AppName = "filebrowser"
	Organizr          AppName = "organizr"
	Unraid            AppName = "unraid"
	Ombi              AppName = "ombi"
	Gitea             AppName = "gitea"
	Pihole            AppName = "pihole"
	Dozzle            AppName = "dozzle"
	Nzbhydra          AppName = "nzbhydra"
	Portaine          AppName = "portaine"
	Guacamol          AppName = "guacamol"
	Netdat            AppName = "netdat"
	Requestr          AppName = "requestr"
	Adguar            AppName = "adguar"
	Gap               AppName = "gap"
	Bitwarde          AppName = "bitwarde"
	Duplicac          AppName = "duplicac"
	Kitan             AppName = "kitan"
	Resilio           AppName = "resilio"
	Moviematc         AppName = "moviematc"
	Peti              AppName = "peti"
	Floo              AppName = "floo"
	UptimeKuma        AppName = "uptime-kuma"
	NginxProxyManager AppName = "nginx-proxy-manager"
	TheLounge         AppName = "thelounge"
	Grafana           AppName = "grafana"
	Monitorr          AppName = "monitorr"
	Logarr            AppName = "logarr"
	PLPP              AppName = "plpp"
	Webtools          AppName = "webtools"
)
